### ISSUE TITLE
RGBHV 

### ISSUE THREAD

**Issue by eimparas** [arithmaldor/SCART-to-VGA#10]
hello i have a scart tv , i want to connect to it a vga source from my emulation pc , from my understanding this is not possibe with that adapter ? but what Exactly makes it imposible ? Sync ? horizontal or vertical refresh rate ?  i know this does not realy classify as an issue but info on this subject is too information is sparse and hard to understand

**Comment by arithmaldor** [comment]
For that you would be going VGA to SCART, if you were able to send a 15khz signal from your PC you could combine the H and V syncs using a sync combining circuit, I recommend https://www.retrorgb.com/building-a-passive-sync-combiner.html.
