### ISSUE TITLE
+5v should be powered by the SCART Cable

### ISSUE THREAD

**Issue by amoore2600** [arithmaldor/SCART-to-VGA#7]
There's is no need to power the LM1881 from USB. Every SCART connection should supply +5v. (All game consoles have +5v)

A second set of jumpers could also be added to switch between SCART +5v and USB +5v Power. Looks like there lots of room on the PCB for it. 

There might be a 180 Ohm resistor needed between the SCART +5V and the LM1881.

here is my hack job of this in action (no 180 ohm resistor).

![IMG_20200306_154706](https://user-images.githubusercontent.com/3682337/76122452-1348fa80-5fc4-11ea-91fe-226f7e0e3a44.jpg)
![JPEG_20200306_155038](https://user-images.githubusercontent.com/3682337/76122456-1512be00-5fc4-11ea-9682-d7cb86b6a285.jpg)

**Comment by mmmonkeyPete** [comment]
How does the fact that some PAL Scart leads output (correctly)  up-to 12v on Scart Pin 8 affect this?

http://members.optusnet.com.au/eviltim/gamescart/gamescart.htm#jaguar
http://members.optusnet.com.au/eviltim/gamescart/gamescart.htm#xbox
http://members.optusnet.com.au/eviltim/gamescart/gamescart.htm#snes (PAL model)
http://members.optusnet.com.au/eviltim/gamescart/gamescart.htm#gamecube (PAL model)
http://members.optusnet.com.au/eviltim/gamescart/gamescart.htm#wii
http://members.optusnet.com.au/eviltim/gamescart/gamescart.htm#dcast
https://nfggames.com/forum2/index.php?topic=4236.0

It looks like the LM1881 is okay receiving between 5 and 12v, but I don't  understand if it affects the output at all?
